name: Silvanus-Dev Dockerization

on:
  workflow_dispatch:
    
env:
  DHUB_UNAME: ${{ secrets.DHUB_UNAME }}
  DHUB_PWORD: ${{ secrets.DHUB_PWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image v0idf1sh/silvanus-dev
      run: docker build . --file Dockerfile --tag v0idf1sh/silvanus-dev
    - name: Log into Docker Hub
      run: docker login -u $DHUB_UNAME -p $DHUB_PWORD
    - name: Push image to Docker Hub v0idf1sh/silvanus-dev
      run: docker push v0idf1sh/silvanus-dev